name: Trigger Release

on:
  push:
    branches:
      - master

jobs:
  check-review:
    runs-on: ubuntu-latest
    steps:
    - name: Validate release PR
      uses: edgedb/action-release/validate-pr@master
      id: release
      continue-on-error: true
      with:
        github_token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}
        version_file: httptools/_version.py
        version_line_pattern: |
          __version__\s*=\s*(?:['"])([[:PEP440:]])(?:['"])
    - name: Trigger release
      uses: edgedb/action-release/trigger@master
      with:
        release_validation_check: "validate-release-request"
